# Generated by Django 4.0 on 2021-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogger_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, help_text='Blogger biography', max_length=1000, null=True),
        ),
    ]
